version: "3.1"

services:

  postgres:
    image: "postgres:9.6.11"
    container_name: "postgres"
    labels:
      NAME: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
