version: 2

aliases:
  - &filter-prod-branch
    branches:
      only:
        - master

  - &root-restore-npm-cache
    keys:
      - v1-dependencies-{{ checksum "package.json" }}
      - v1-dependencies-

  - &save-cache
    paths:
        - node_modules
    key: v1-dependencies-{{ checksum "package.json" }}

  - &npm-install
    name: Install npm dependencies
    command: |
      npm install

defaults: &defaults
  docker:
    - image: circleci/node:12
  working_directory: ~/app

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *root-restore-npm-cache
      - run: *npm-install
      - save_cache: *save-cache
      # - run:
      #     name: Run linter and tests
      #     command: npm test

  deploy-prod:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *root-restore-npm-cache
      - run: *npm-install
      - save_cache: *save-cache
      - run: npm run migrate
      - run: npm run seed:all
      - run: npm run deploy

workflows:
  version: 2

  # Avoid Prod releases adding approval step and different configs
  build-deploy-prod:
    jobs:
      - build:
          filters: *filter-prod-branch
      - hold:
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # We only run the "hold" job when build has succeeded
           - build
      - deploy-prod:
          requires:
            - hold
